[features]
seeds = false
skip-lint = false

[programs.localnet]
justies = "4PMBVVw4YG1Cmni7zABSdJ2Z4AAatQBDzJFisfZ3M6Rd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./.local-solana-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "4PMBVVw4YG1Cmni7zABSdJ2Z4AAatQBDzJFisfZ3M6Rd"
program = "target/deploy/justies.so"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "BPFLoaderUpgradeab1e11111111111111111111111"
